### ISSUE TITLE
Missing talk abstract

### ISSUE THREAD

**Issue by Amygos** [promcon/website#105]
The link to the abstract of the talk *"Prometheus in Small and Medium Businesses: Why You Don't Need to Do Rocket Science (Kubernetes) to Use It"* is broken.
I think due missing file:

`website/content/2019-munich/talks/prometheus-in-small-and-medium-businesses-why-you-don-t-need-to-do-rocket-science-kubernetes-to-use-it.md`

**Comment by juliusv** [comment]
Sorry, that was my fault! After renaming the file I apparently didn't add it to git correctly. Fix is pushed, thanks for letting us know.
