### ISSUE TITLE
Sponsor Logos Added to Website

### ISSUE THREAD

**Issue by debgiles** [promcon/website#52]
Please help with adding logos & URLs for Robust Perception, InfluxData, FreshTracks, CNCF, and Origoss Solutions to the website.

I’m tracking logos received & URL’s, along with all other sponsor deliverables in our Planning Doc (removed link to non-public document -- RichiH), as well as saving all logos in [this folder](https://drive.google.com/drive/u/1/folders/1c3Zw7ny6fXKZsPDykQgwYAiDYmWQRRew) for reference when it’s time for signage.

**Comment by juliusv** [comment]
@debgiles While we haven't received a logo from FreshTracks yet, I've just used the one from their website in https://github.com/promcon/website/pull/53, which is a scalable SVG, so should be fine.
