### ISSUE TITLE
Add GitLab as Social Event Sponsor to Website

### ISSUE THREAD

**Issue by debgiles** [promcon/website#55]
Logos: https://drive.google.com/drive/u/1/folders/1gj1A7Zr69A2ZG94qRaKUJ1tjfLRPD45L

URL: https://about.gitlab.com/?utm_medium=display&utm_source=event&utm_campaign=promcon

**Comment by juliusv** [comment]
Pull request for this is at https://github.com/promcon/website/pull/56

**Comment by juliusv** [comment]
Done.

**Comment by debgiles** [comment]
Thank you!

Deb Giles
Meeting and Event Planner
The Linux Foundation
+1.503.807.1876 <javascript:void(0);> (Time Zone: Central Time)
