### ISSUE TITLE
Add Sysdig logo to website

### ISSUE THREAD

**Issue by debgiles** [promcon/website#61]
Please add the Sysdig logo to the website as a Diamond sponsor, directing to the URL: www.sysdig.com

Thanks!

**Comment by debgiles** [comment]
Please update the Diamond sponsor logos to be in alphabetical order.
CNCF
FreshTracks.io
influxdata
Robust Perception
Sysdig

Thanks!

**Comment by juliusv** [comment]
@debgiles So far we sorted by date of contract signing, is alphabetical order what the LF usually does?

**Comment by debgiles** [comment]
Hi Julius,

Yes, we do everything in alphabetical order so no preference is shown to
any one sponsor.

Thanks,

Deb

Deb Giles
Meeting and Event Planner
The Linux Foundation
+1.503.807.1876 <javascript:void(0);> (Time Zone: Central Time)

**Comment by juliusv** [comment]
@debgiles Ok! Sysdig logo addition and reordering is out at https://github.com/promcon/website/pull/62

**Comment by debgiles** [comment]
Thanks!

Deb Giles
Meeting and Event Planner
The Linux Foundation
+1.503.807.1876 <javascript:void(0);> (Time Zone: Central Time)
