### ISSUE TITLE
Add Wavefront as Diamond Sponsor

### ISSUE THREAD

**Issue by debgiles** [promcon/website#74]
Please help add Wavefront as a Diamond sponsor to the website.

Logo: https://drive.google.com/drive/u/0/folders/1kAgb0RPyWvSw4sU3kWRhd3rD8yJtSnoK
URL: www.wavefront.com

Thanks!

**Comment by juliusv** [comment]
PR for this out in https://github.com/promcon/website/pull/75.

**Comment by RichiH** [comment]
Done.
